version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dummy-data"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r5z0n2accwdb"
s3_prefix = "dummy-data"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
